name: Build and push to GHCR

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Make repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's/^Hikari-Systems\///')" >> $GITHUB_ENV
      - name: Make branch name
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's/^refs\/heads\///')" >> $GITHUB_ENV
      - name: Make target architectures
        run: echo "TARGET_ARCHITECTURES=linux/amd64,linux/arm64" >> $GITHUB_ENV
      - uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.TARGET_ARCHITECTURES }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.TARGET_ARCHITECTURES }}
      - name: Log in to the Github container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      # - name: Setup AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ env.TARGET_ARCHITECTURES }}
          build-args: |
            GH_API_KEY=${{ secrets.GH_TOKEN }}
          tags: |
            ghcr.io/hikari-systems/${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/hikari-systems/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}
            ghcr.io/hikari-systems/${{ env.REPO_NAME }}:latest
            # ${{ vars.ECR_DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}
            # ${{ vars.ECR_DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}
            # ${{ vars.ECR_DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:latest
  
