name: Build and push to GHCR

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:3.0.0-beta.1
        env:
          REGISTRY_STORAGE: s3
          REGISTRY_STORAGE_S3_ACCESSKEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REGISTRY_STORAGE_S3_SECRETKEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGISTRY_STORAGE_S3_REGION: ${{ secrets.AWS_REGION }}
          REGISTRY_STORAGE_S3_BUCKET: hikari-docker-registry
          REGISTRY_HTTP_ADDR: :5000
          REGISTRY_HTTP_SECRET: ${{ secrets.DOCKER_REGISTRY_SECRET }}
        ports:
          - 5000:5000      
    steps:
      - name: Make repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's/^Hikari-Systems\///')" >> $GITHUB_ENV
      - name: Make branch name
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's/^refs\/heads\///')" >> $GITHUB_ENV
      - name: Make target architectures
        run: echo "TARGET_ARCHITECTURES=linux/amd64,linux/arm64" >> $GITHUB_ENV
      - uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.TARGET_ARCHITECTURES }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.TARGET_ARCHITECTURES }}
          driver-opts: network=host
      - name: Log in to the Github container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      # - name: Setup AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ env.TARGET_ARCHITECTURES }}
          secrets: |
            "ghapikey=${{ secrets.GH_TOKEN }}"
          tags: |
            ghcr.io/hikari-systems/${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/hikari-systems/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}
            ghcr.io/hikari-systems/${{ env.REPO_NAME }}:latest
            localhost:5000/${{ env.REPO_NAME }}:${{ github.sha }}
            localhost:5000/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}
            localhost:5000/${{ env.REPO_NAME }}:latest
  
